### ISSUE TITLE
Question about refractoring code structure

### ISSUE THREAD

**Issue by SyluxDX** [kavulox/xArtix#5]
Hi, I've been trying to solve some bugs in the interactive mode and have done a major refactor of the scripts structure, separating the code for interaction, color and password generator.
Are your ok with theses changes on a pull request, or do you want a single file script?

**Comment by Cobalt-Inferno** [comment]
> Hi, I've been trying to solve some bugs in the interactive mode and have done a major refactor of the scripts structure, separating the code for interaction, color and password generator. Are your ok with theses changes on a pull request, or do you want a single file script?

Yeah thats completely fine. I've been meaning to do it lately anyway, but I've been quite busy.
